---
- name: Prepare host
  include_tasks: prepare_host.yml

- name: Download Velocity
  include_tasks: download.yml

- name: Install Velocity
  include_tasks: install.yml

- name: Systemd
  include_tasks: systemd.yml
# handle restart\reload with handler
