---

- name: Create user
  ansible.builtin.user:
    name: "{{ velocity_unix_user }}"
    state: present
    create_home: False

- name: Install Java
  apt:
    pkg: default-jre
  when: not (velocity_skip_install_java | bool)

- name: Initialzie deploy helper
  deploy_helper:
    path: "{{ velocity_rootdir }}"
    state: "present"
    release: "{{ velocity_version }}"

- name:
  ansible.builtin.file:
    path: "{{ deploy_helper.new_release_path }}"
    state: directory
    owner: "{{ velocity_unix_user }}"
    group: "{{ velocity_unix_group }}"
    mode: "744"
