---
- name: Make systemd service
  ansible.builtin.template:
    src: "templates/velocity.service.jinja"
    dest: "/etc/systemd/system/{{ velocity_unix_user }}.service"
    mode: 755
    owner: "root"
    group: "root"
  notify:
    - Reload systemd
    - Restart Velocity service

- name: Make systemd socket
  ansible.builtin.template:
    src: "templates/velocity.socket.jinja"
    dest: "/etc/systemd/system/{{ velocity_unix_user }}.socket"
    mode: 755
    owner: "root"
    group: "root"
  notify:
    - Reload systemd
    - Restart Velocity socket
